name: CI Pipeline

on:
  push:
    branches: ["main", "develop"]
  pull_request:
    branches: ["main", "develop"]

jobs:
  backend:
    name: Backend (Go)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Install dependencies
        run: go mod tidy

      - name: Lint
        run: go vet ./...

      - name: Build
        run: go build -v ./...

      - name: Run Tests
        run: go test ./...

  frontend:
    name: Frontend (React PWA)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          cd front-end-PWA
          npm install

      - name: Lint (ESLint)
        run: |
          cd front-end-PWA
          npm run lint

      - name: Build
        run: |
          cd front-end-PWA
          npm run build

      # - name: Deploy to production (disabled)
      #   run: echo "Deploy script here"
      
on:
  push:
    branches: ["main", "develop"]
jobs:
  backend:
    name: Backend
  frontend:
    name: Frontend