services:
  backend:
    restart: unless-stopped
    volumes:
      - ./backend:/app
    environment:
      - LOG_LEVEL=debug
      - DATABASE_URL=root:root@tcp(mysql_container:3306)/centaurus?charset=utf8mb4&parseTime=True&loc=Local

  frontend-pwa:
    build:
      target: dev
    command: ["npm", "start"]
    volumes:
      - ./front-end-PWA:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_API_HOST=http://localhost:8080
    restart: unless-stopped
    # volumes:
    #   - ./front-end-PWA:/usr/share/nginx/html

  mysql:
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=centaurus
      - MYSQL_USER=dev
      - MYSQL_PASSWORD=devpassword
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    restart: unless-stopped
