services:
  backend:
    build:
      context: ./backend
      target: runtime
    image: backend:preprod
    environment:
      - DATABASE_URL=root:root@tcp(mysql_container:3306)/centaurus?charset=utf8mb4&parseTime=True&loc=Local
    ports:
      - "8080:8080"
    networks:
      - app_network
    depends_on:
      - mysql

  frontend-pwa:
    build:
      context: ./front-end-pwa
      dockerfile: Dockerfile
      target: prod
      args:
        REACT_APP_API_URL: /api
    image: frontend-pwa:preprod
    environment:
      - REACT_APP_API_URL=/api
    ports: 
      - "80:80"
      - "443:443"
    volumes:
      - ./front-end-pwa/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt:ro
    networks:
      - app_network
    depends_on: 
      - backend

  mysql:
    image: mysql:8.0
    env_file:
      - .env
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_network

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8081:80"
    environment:
      - PMA_HOST=mysql
    restart: unless-stopped
    networks:
      - app_network

  #nginx:
  #  image: nginx:stable-alpine
  #  ports:
  #    - "80:80"
  #  volumes:
  #    - ./front-end-pwa/nginx.conf:/etc/nginx/nginx.conf:ro
  #  depends_on:
  #    - backend
  #    - frontend-pwa
  #  networks:
  #    - app_network

networks:
  app_network:

volumes:
  mysql_data:
