# Etape 1 : build de l'application
FROM golang:1.23-alpine AS builder

#Définir le répertoire de travail
WORKDIR /app

#copier les fichier go mod 
COPY go.mod go.sum ./
RUN go mod download

#COPIER tout le code source
COPY . .

#COMPILER l'application
RUN go build -o main .

# Etape 2 : Image finale
FROM alpine:latest

WORKDIR /root/

# Installer `mysql-client` pour attendre MySQL
RUN apk add --no-cache mysql-client

#Copier l'exécutable depuis le build
COPY --from=builder /app/main .
RUN chmod +x /root/main

# Copier l'entrypoint et Donner les permissions d'execution à entrypoint.sh
COPY entrypoint.sh /app/entrypoint.sh
RUN chmod +x /app/entrypoint.sh

#Exposer le port 
EXPOSE 8080

#Utilser l'entrypoint pour attendre MySql
ENTRYPOINT [ "/app/entrypoint.sh" ]

# Lancer l'application
CMD ["/app/main"]