basePath: /
definitions:
  model.Credential:
    properties:
      email:
        type: string
      id:
        type: integer
      password:
        type: string
      username:
        type: string
    required:
    - email
    - password
    type: object
  model.Horses:
    properties:
      age:
        type: integer
      createdAt:
        type: string
      fk_user_id:
        type: integer
      id:
        type: integer
      name:
        type: string
      race:
        type: string
      updatedAt:
        type: string
    required:
    - age
    - fk_user_id
    - name
    - race
    type: object
  model.User:
    properties:
      createdAt:
        type: string
      email:
        type: string
      password:
        type: string
      updatedAt:
        type: string
      username:
        type: string
    required:
    - email
    - password
    - username
    type: object
  model.Weights:
    properties:
      CreatedAt:
        type: string
      FkHorseId:
        type: integer
      UpdateddAt:
        type: string
      date:
        type: string
      diiferenceWeight:
        type: integer
      id:
        type: integer
      lastWeight:
        type: integer
      weight:
        type: integer
    required:
    - date
    - weight
    type: object
host: localhost:8080
info:
  contact: {}
  description: Example of a user API with Swagger.
  title: API
  version: "1.0"
paths:
  /api/v1/auth/sign-in:
    post:
      consumes:
      - application/json
      description: Signin  a user
      parameters:
      - description: Email and password
        in: body
        name: credential
        required: true
        schema:
          $ref: '#/definitions/model.Credential'
      produces:
      - application/json
      responses:
        "200":
          description: User connected
          schema:
            $ref: '#/definitions/model.Credential'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Signin a user
      tags:
      - Credential
  /api/v1/auth/sign-up:
    post:
      consumes:
      - application/json
      description: Register a new user
      parameters:
      - description: Username, Email and Password
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/model.User'
      produces:
      - application/json
      responses:
        "200":
          description: User created successfully
          schema:
            $ref: '#/definitions/model.User'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Register a new user
      tags:
      - Credential
  /api/v1/horse/:id:
    delete:
      consumes:
      - application/json
      description: Delete horse
      parameters:
      - description: Horse ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Horses récupéré
          schema:
            $ref: '#/definitions/model.Horses'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: delete a horse
      tags:
      - Horses
    get:
      consumes:
      - application/json
      description: get last weight horse and date
      parameters:
      - description: Horse Id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Weight add
          schema:
            $ref: '#/definitions/model.Weights'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: get last a weight horse
      tags:
      - Weights
    post:
      consumes:
      - application/json
      description: add a weight horse
      parameters:
      - description: Weight, fk_horse_id
        in: body
        name: addhorse
        required: true
        schema:
          $ref: '#/definitions/model.Weights'
      produces:
      - application/json
      responses:
        "201":
          description: Weight add
          schema:
            $ref: '#/definitions/model.Weights'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: add a weight horse
      tags:
      - Weights
    put:
      consumes:
      - application/json
      description: add a profil user
      parameters:
      - description: Name, Age and Race
        in: body
        name: addhorse
        required: true
        schema:
          $ref: '#/definitions/model.Horses'
      produces:
      - application/json
      responses:
        "201":
          description: Horse created
          schema:
            $ref: '#/definitions/model.Horses'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Update a horse
      tags:
      - Horses
  /api/v1/horse/{id}:
    get:
      consumes:
      - application/json
      description: Retrieve a horse for a specific user
      parameters:
      - description: Horse Id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "201":
          description: Horse retrieved
          schema:
            $ref: '#/definitions/model.Horses'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get a horse
      tags:
      - Horses
  /api/v1/horses/{id}:
    get:
      consumes:
      - application/json
      description: Retrieve a list of horses for a specific user
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Horses récupéré
          schema:
            $ref: '#/definitions/model.Horses'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: get a list of horses
      tags:
      - Horses
  /api/v1/horses/add-horse:
    post:
      consumes:
      - application/json
      description: add a  horse
      parameters:
      - description: Name, Age and Race
        in: body
        name: addhorse
        required: true
        schema:
          $ref: '#/definitions/model.Horses'
      produces:
      - application/json
      responses:
        "201":
          description: Horse created
          schema:
            $ref: '#/definitions/model.Horses'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: add a horse
      tags:
      - Horses
  /ping:
    get:
      description: Respond with "pong"
      produces:
      - application/json
      responses:
        "200":
          description: pong
          schema:
            type: string
      summary: Ping
      tags:
      - example
swagger: "2.0"
