basePath: /
definitions:
  model.Credential:
    properties:
      email:
        type: string
      id:
        type: integer
      password:
        type: string
      username:
        type: string
    required:
    - email
    - password
    type: object
  model.User:
    properties:
      createdAt:
        type: string
      email:
        type: string
      password:
        type: string
      updatedAt:
        type: string
      username:
        type: string
    required:
    - email
    - password
    - username
    type: object
host: localhost:8080
info:
  contact: {}
  description: Example of a user API with Swagger.
  title: API
  version: "1.0"
paths:
  /api/auth/sign-in:
    post:
      consumes:
      - application/json
      description: Signin  a user
      parameters:
      - description: Email and password
        in: body
        name: credential
        required: true
        schema:
          $ref: '#/definitions/model.Credential'
      produces:
      - application/json
      responses:
        "200":
          description: User connected
          schema:
            $ref: '#/definitions/model.Credential'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Signin a user
      tags:
      - Credential
  /api/auth/sign-up:
    post:
      consumes:
      - application/json
      description: Register a new user
      parameters:
      - description: Username, Email and Password
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/model.User'
      produces:
      - application/json
      responses:
        "200":
          description: User created successfully
          schema:
            $ref: '#/definitions/model.User'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Register a new user
      tags:
      - Credential
  /ping:
    get:
      description: Respond with "pong"
      produces:
      - application/json
      responses:
        "200":
          description: pong
          schema:
            type: string
      summary: Ping
      tags:
      - example
swagger: "2.0"
