info:
  contact: {}
paths:
  /ping:
    get:
      description: Respond with "pong"
      produces:
      - application/json
      responses:
        "200":
          description: pong
          schema:
            type: string
      summary: Ping tesstt
      tags:
      - example
swagger: "2.0"
