services:
  frontend-pwa:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        api_url: "http://localhost:5000" # EN LOCAL
        # api_url: "https://api-preprod.example.com" EN PREPROD
        # api_url: "https://api.example.com" EN PROD
    ports:
      - "3000:80"
    restart: always
